name: Release Please

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

  release:
    runs-on: macos-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4

      - uses: nekowinston/setup-deno@v2

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5"

      - name: Build
        run: deno task build
        env:
          COMPILE_APPLE_COLOR_LIST: 1

      - name: Publish NPM package
        working-directory: dist/npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_DEPLOY_TOKEN}}

      - name: Publish to JSR
        run: deno publish

      - name: Upload the palette files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Creating tarball"
          tar cvzf catppuccin.tar.gz --directory=dist/palettes/ . || exit 1
          echo "Creating zip"
          pushd dist/palettes && zip -r "$GITHUB_WORKSPACE/catppuccin.zip" ./* && popd || exit 1
          echo "Uploading release assets"
          gh release upload ${{ needs.release-please.outputs.tag_name }} catppuccin.zip catppuccin.tar.gz --clobber
